name: 'train-SR-LLM-Enhanced'
device: 'cuda:0'
seed: 42
output_dir: ./work_dirs
num_workers: 12
resume: null  # 如果存在，则恢复训练
# prompt: 'Buildings with changes, Mound changes.'
prompt: 'Analyze the multi-temporal Arctic remote sensing images, infer the retrogressive thaw slump evolution types, detect the precise slump change boundaries and extract the spatial deformation features.'
onnx_weights: './examples/ONNXRuntime/weights'

data:
  data_root: './data/change'
  # data_format: 'custom'                           # [default, custom]
  data_format: 'default'
  transforms:
    apply_prob: 0.5                               # 应用概率
    color_jitter: 0.2                             # 颜色抖动
    rotation_degree: 90                           # 旋转角度
    gamma_range: [0.8, 1.2]                       # Gamma矫正
    affine_degree: 15                              # 仿射变换
    erase_prob: 0.3                                 # 随机擦除
    erase_ratio: [0.02, 0.15]                           # 随机擦除大小
    blur_sigma: 0.3                               # 高斯模糊
    clahe: 0.5                                    # 直方图均衡化


model:
  num_classes: 1
  backbone_name: "swin_base_patch4_window7_224"   # ['swin_base_patch4_window7_224', 'resnet50', 'hgnetv2']
  bev_name: "LinearAttention"                     # [LinearAttention, Transformer]
  fpn_type: "L-FPN"                               # ['FPN', 'L-FPN']
  use_ega: true                                   # 是否使用 边缘-高斯聚合（EGA）模块
  diff_attention: "CBAM"                          # ['SE', 'CBAM']
  out_dims: [256, 256, 256, 256]
  use_token_connector: False                      # 是否降低 token 维度
  pretrained: True                                # 是否使用预训练的模型参数
  img_size: 256
  text_encoder_name: "microsoft/phi-1_5"          # [microsoft/phi-1_5, bert-base-uncased]
  desc_embs: null                                 # 文本描述向量地址 "./weights/embeddings.pt"
  freeze_text_encoder: False                      # 冻结模型参数
  use_rts_constraint: False                        # 开启RTS物理约束

loss:
  weight_ce: 1.0  # 分类损失权重
  weight_dice: 1.5  # 边缘分割损失权重
  weight_focal: 1.5  # 类别不平衡损失权重
  alpha: 0.6  # Focal损失正负样本平衡系数
  gamma: 2.0  # Focal损失聚焦参数
  weight_bcl: 0.3  # 特征区分损失权重
  weight_rts_cons: 0  # RTS物理一致性损失权重（新增）

logger:
  log_name: 'Seg_log'
  level: 'INFO'

training:
  start_epoch: 1
  epochs: 200
  scheduler: 'step'  # [step, plateau]
  lr: 0.0001
  lr_backbone: 0.00001
  lr_drop: 80
  weight_decay: 0.0001
  batch_size: 4
  eval_freq: 1
  start_eval: 1
  threshold: 0.5

test:
  img_dirs: './data/change/test'
  batch_size: 1
  threshold: 0.5
  postprocess: False  # 控制是否应用后处理
  device: 'cuda:0'
  name: "test"
  weights_dir: '.work_dirs/train-SR/checkpoints/best_iou.pth'
  save_dir: "./work_dirs"
  show: True
  show_overlay: False

infer:
  name: 'BL2_5'
  input_dir: '/hdd10Ta/chenyf/Valid/SR-TP'
  chunk_size: 25600  # 25600
  postprocess: False  # 控制是否应用后处理
  weights_dir: '/hdd10Ta/chenyf/SegChange-R1/work_dirs/train-SR_3/checkpoints/best_iou.pth'
  output_dir: './outputs/iou-0.43/valid'
  threshold: 0.5
  device: 'cuda:0'
